"""Runtime for block programs (user story US-003).

A program is Python text generated by the block editor. It is executed with
these names injected: ``mip`` (the robot), ``program`` (this runtime, for
event registration), ``sensors`` (cached sensor values), ``_step`` (block
highlighting hook) plus ``asyncio``, ``math`` and ``random``.

The text defines ``async def main(mip)`` and/or event handlers registered
with ``program.on_clap(...)`` etc. :meth:`Program.run` executes ``main``,
then keeps running while any event handler or timer is registered, until
:meth:`Program.stop` is called or the robot disconnects.
"""

import asyncio
import inspect
import math
import random

from . import protocol as p

STATES = ("idle", "running", "finished", "stopped", "stopped (disconnected)", "error")


class ProgramError(Exception):
    """Raised for problems in the program text itself (syntax, missing main)."""


class Sensors:
    """Async accessors for the values the robot last reported.

    Values come from the runtime's status cache (fed by every notification);
    a value that was never reported is queried once from the robot.
    """

    def __init__(self, program):
        self._p = program

    async def _get(self, key, opcode):
        if key not in self._p.status:
            try:
                await self._p.mip.request(opcode, timeout=1.5)
            except (TimeoutError, ConnectionError):
                pass
        return self._p.status.get(key)

    async def battery(self):
        return await self._get("battery", p.CMD_GET_STATUS)

    async def position(self):
        code = await self._get("position", p.CMD_GET_STATUS)
        return p.POSITIONS.get(code, "unknown") if code is not None else "unknown"

    async def odometer(self):
        return await self._get("odometer_cm", p.CMD_GET_ODOMETER)

    async def radar(self):
        return p.RADAR.get(self._p.status.get("radar"), "no object")

    async def gesture(self):
        return p.GESTURES.get(self._p.status.get("gesture"), "none")

    async def claps(self):
        return self._p.status.get("claps", 0)


class Program:
    def __init__(self, mip, *, on_state=None, log=None):
        self.mip = mip
        self.on_state = on_state      # (state, block_id, error_text) -> None
        self.log = log                # (text) -> None
        self.status = {}
        self.state = "idle"
        self.current_block = None
        self._handlers = []           # (kind, matcher, fn)
        self._timers = []             # (seconds, fn)
        self._tasks = set()
        self._main_task = None
        self._stop_reason = None
        self._prev_notification = None

    # -- registration API used by generated code -----------------------------

    def on_clap(self, fn, count=None):
        self._handlers.append(("clap", (lambda f: count is None or f.get("claps") == count), fn))

    def on_gesture(self, fn, gesture=None):
        self._handlers.append(("gesture", (lambda f: gesture is None or p.GESTURES.get(f.get("gesture")) == gesture), fn))

    def on_radar(self, fn, radar=None):
        self._handlers.append(("radar", (lambda f: radar is None or p.RADAR.get(f.get("radar")) == radar), fn))

    def on_position(self, fn, position=None):
        self._handlers.append(("position", (lambda f: position is None or p.POSITIONS.get(f.get("position")) == position), fn))

    def every(self, seconds, fn):
        self._timers.append((max(0.05, float(seconds)), fn))

    # -- events ----------------------------------------------------------------

    def _on_notification(self, data):
        # Read the previous position before the dashboard's handler (which may
        # share this status dict) overwrites it.
        previous_position = self.status.get("position")
        if self._prev_notification:
            self._prev_notification(data)
        name, fields = p.decode_reply(data)
        updates = {k: v for k, v in fields.items() if k != "text"}
        opcode = data[0] if data else None
        kind = {p.CMD_CLAP_DETECTED: "clap", p.CMD_GESTURE_DETECTED: "gesture",
                p.CMD_RADAR_RESPONSE: "radar"}.get(opcode)
        if opcode == p.CMD_GET_STATUS and "position" in updates:
            if updates["position"] != previous_position:
                kind = "position"
        self.status.update(updates)
        if kind and self.state == "running":
            for h_kind, matcher, fn in self._handlers:
                if h_kind == kind and matcher(updates):
                    self._spawn(fn)

    def _spawn(self, fn):
        task = asyncio.ensure_future(self._call(fn))
        self._tasks.add(task)
        task.add_done_callback(self._tasks.discard)

    async def _call(self, fn):
        try:
            result = fn(self.mip)
            if inspect.isawaitable(result):
                await result
        except asyncio.CancelledError:
            raise
        except Exception as e:
            self._fail(e)

    async def _timer(self, seconds, fn):
        while True:
            await asyncio.sleep(seconds)
            await self._call(fn)

    async def _step(self, block_id):
        self.current_block = block_id
        if self.on_state:
            self.on_state("running", block_id, None)
        await asyncio.sleep(0)

    def _set_state(self, state, block=None, error=None):
        self.state = state
        if self.on_state:
            self.on_state(state, block, error)

    def _fail(self, exc):
        if self.state != "running":
            return
        text = f"{type(exc).__name__}: {exc}" if str(exc) else type(exc).__name__
        if self.log:
            self.log(f"error at block {self.current_block}: {text}")
        self._stop_reason = ("error", self.current_block, text)
        self._cancel_all()

    # -- lifecycle -------------------------------------------------------------

    def namespace(self):
        return {"mip": self.mip, "program": self, "sensors": Sensors(self), "_step": self._step,
                "asyncio": asyncio, "math": math, "random": random}

    async def run(self, code):
        """Execute program ``code``; returns the final state."""
        if self.state == "running":
            raise ProgramError("a program is already running")
        ns = self.namespace()
        try:
            compiled = compile(code, "<program>", "exec")
            exec(compiled, ns)
        except SyntaxError as e:
            raise ProgramError(f"syntax error line {e.lineno}: {e.msg}") from None
        main = ns.get("main")
        if main is None and not self._handlers and not self._timers:
            raise ProgramError("program has no 'when program starts' block and no events")

        self._stop_reason = None
        self.current_block = None
        self._prev_notification = self.mip.on_notification
        self.mip.on_notification = self._on_notification
        self._set_state("running")
        try:
            for seconds, fn in self._timers:
                self._spawn_timer(seconds, fn)
            if main is not None:
                self._main_task = asyncio.ensure_future(self._call(main))
                await self._wait(self._main_task)
            if self._stop_reason is None and (self._handlers or self._timers):
                # Event-driven program: live until stopped.
                await self._wait(asyncio.ensure_future(asyncio.Event().wait()))
            while self._stop_reason is None and self._tasks:
                await self._wait(next(iter(self._tasks)))
            if self._stop_reason is None:
                self._set_state("finished")
        finally:
            self._cancel_all()
            self.mip.on_notification = self._prev_notification
            if self._stop_reason is not None:
                self._set_state(*self._stop_reason)
            if self.state == "running":
                self._set_state("stopped")
        return self.state

    def _spawn_timer(self, seconds, fn):
        task = asyncio.ensure_future(self._timer(seconds, fn))
        self._tasks.add(task)
        task.add_done_callback(self._tasks.discard)

    async def _wait(self, task):
        self._tasks.add(task)
        try:
            await task
        except asyncio.CancelledError:
            if self._stop_reason is None:
                raise
        finally:
            self._tasks.discard(task)

    def _cancel_all(self):
        for t in list(self._tasks):
            t.cancel()
        if self._main_task and not self._main_task.done():
            self._main_task.cancel()

    def stop(self, reason="stopped"):
        """Stop a running program (``reason`` becomes the final state)."""
        if self.state != "running":
            return
        self._stop_reason = (reason, None, None)
        self._cancel_all()

    async def stop_and_halt(self, reason="stopped"):
        """Stop the program and make sure the robot is not moving."""
        self.stop(reason)
        try:
            await self.mip.stop()
        except Exception:
            pass
